development:
  access_key_id: AKIAJOQEZZJLJFVJS77Q
  secret_access_key: <%= ENV['CODAW_DEV_S3_ACCESS_KEY'] %>

staging:
  access_key_id: AKIAJMPG3AA3THH4NTCA
  secret_access_key: <%= ENV['CODAW_PROD_S3_ACCESS_KEY'] %>

production:
  access_key_id: AKIAJMPG3AA3THH4NTCA
  secret_access_key: <%= ENV['CODAW_PROD_S3_ACCESS_KEY'] %>
