development:
  access_key_id: AKIAJFXX4GKRZ2ADTA4Q
  secret_access_key: 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

staging:
  access_key_id: AKIAJMPG3AA3THH4NTCA
  secret_access_key: <%= ENV['CODAW_PROD_S3_ACCESS_KEY'] %>

production:
  access_key_id: AKIAJMPG3AA3THH4NTCA
  secret_access_key: <%= ENV['CODAW_PROD_S3_ACCESS_KEY'] %>
