# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b9db99ef7acc05b0bd6cfa32629ab7a64e93c2cac02afb7726fc8eaa96e70ba31dc1d45f563d1235011224907108505c72cc967d7e9707129a482d55237d1bd

test:
  secret_key_base: 7fc7550e31070d5ca4c133bdf7e52e93cd9e66853a4e5f98ada2cddde4eb7ba35969f480c781fe2400f5bf7a12c1ee17e6c0ebd8a98b212e382cc427b70fd233

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
