# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83eb00361e91a2374693ab7eb448f1c58c3926c9807a0c13eb7d078260d8ead1e2d2a93dac3eda6fc28824b1f1c72999bacd0deb71624139b53e6927fd577d26

test:
  secret_key_base: 3f6fa96569de44852d018681bca3bcb04ef9666ace6c3754a080d3408d5dc893202782c618789e842fa3b3756e5b5144232ccd4e4b20f037302c9d9be2806cb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # For security, set this as an environment variable
  # change using rake secret RAILS_ENV=production
  secret_key_base: <%= ENV["CODAW_SECRET_KEY_BASE"] %>
